include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    use_super_parameters: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: ignore
    lines_longer_than_80_chars: ignore