// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJQeiX4WArA8d4Ljl_j7e9ymbcugZkFk4',
    appId: '1:4705323814:web:524110563fa25edc76cfe7',
    messagingSenderId: '4705323814',
    projectId: 'todo-fall-2024-0',
    authDomain: 'todo-fall-2024-0.firebaseapp.com',
    storageBucket: 'todo-fall-2024-0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqRWaq7xzyMT96jYbUmao7JYFwBg47Cxk',
    appId: '1:4705323814:android:1f5cd85a35de7b1776cfe7',
    messagingSenderId: '4705323814',
    projectId: 'todo-fall-2024-0',
    storageBucket: 'todo-fall-2024-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjhYRTWQBDfixU3P82jE93wo5Kl0pS9SQ',
    appId: '1:4705323814:ios:61d8fb2b95cb98cb76cfe7',
    messagingSenderId: '4705323814',
    projectId: 'todo-fall-2024-0',
    storageBucket: 'todo-fall-2024-0.appspot.com',
    iosBundleId: 'edu.todo.fall20240.todoFall20240',
  );
}
